version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - TZ=Asia/Singapore
      - PORT=4000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_NAME=${DB_NAME}
    depends_on:
      - redis
      - mysql
    volumes:
      - ./logs:/app/logs

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
  mysql-db-data:
